<?php
//chamando as classes
$post = new Post();
$postController = new PostController();
$categoria = new Categoria();
$helper = new Helper();

//iniciando as paginação
if (empty($_GET['pg'])):
else:
    $pg = $_GET['pg'];
endif;
if (isset($pg)):
    $pg = $_GET['pg'];
else:
    $pg = 1;
endif;

//deletando o post
$del = filter_input(INPUT_GET, "del", FILTER_SANITIZE_NUMBER_INT);
if ($del):
    $post = $postController->retornaPostImagem($del);
    echo $capa = "../upload/" . $post->getThumb();
    if (file_exists($capa) && !is_dir($capa)):
        unlink($capa);
    endif;
    if ($postController->Excluir($del)):
        $resultado = "<div class=\"alert alert-success\">O Post </b> foi removido com sucesso</div>";
    else:
        $resultado = "<div class=\"alert alert-danger\">Erro ao remover </div>";
    endif;
endif;

//quantidade de postagem para visualizar por pagina
$quantidade = 6;
$inicio = ($pg * $quantidade) - $quantidade;
$listarPost = $postController->ListarPost($inicio, $quantidade);
?>

<div class="main-panel">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="#">Listar Posts</a>
            </div>
            <?php require_once './inc/header_top.php'; ?>
        </div>
    </nav>

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Listagem de Posts</h4>                
                        </div>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-striped">
                                <thead>
                                <th>ID</th>
                                <th>Capa</th>
                                <th>Titulo</th>
                                <th>Categoria</th> 
                                <th>Descrição</th>                                 
                                <th>Data</th> 
                                <th>Status</th>                            
                                <th>Ações</th>                                               
                                </thead>
                                <tbody>                                 
                                    <?php                                    
                                    if ($listarPost == null):
                                        echo '<tr><td colspan="8">Não possui nenhum post no momento</td></tr>';
                                    else:
                                        foreach ($listarPost as $pacote):
                                            ?>
                                            <tr>
                                                <td><?= $pacote->getCod(); ?></td>
                                                <td><img src="<?= HOME; ?>/tim.php?src=upload/<?= $pacote->getThumb(); ?>&w=150&h=80&zc=0"></td>
                                                <td><?= $helper->Words($pacote->getTitulo(), 5); ?></td>
                                                <td><?= $pacote->getCategoria()->getTitulo(); ?></td>
                                                <td><?= $helper->Words(html_entity_decode($pacote->getDescricao()), 5); ?></td>                                                                                                  
                                                <td><?= $pacote->getData(); ?></td>
                                                <td>
                                                    <?=
                                                    ($pacote->getStatus() == 1) ?
                                                            '<td><btn class="btn btn-fill btn-success btn-icon">'
                                                            . '<i class="fa ti-check"></i>'
                                                            . '</btn></td>' :
                                                            '<td><btn class="btn btn-fill btn-danger btn-icon">'
                                                            . '<i class="fa fa-times"></i>'
                                                            . '</btn></td>'
                                                    ?>
                                                </td>

                                                <td>
                                                    <a href="?pagina=editarPost&cod=<?= $pacote->getCod(); ?>" class="btn btn-icon btn-primary"><i class="ti-pencil-alt2"></i></a>
                                                    <a href="?pagina=listarPost&del=<?= $pacote->getCod(); ?>" class="btn btn-icon btn-danger" onclick="return confirm('Deseja realmente excluir a <?= $pacote->getTitulo(); ?>');"><i class="ti-close"></i></a>
                                                </td>                                  
                                            </tr>
                                            <?php
                                        endforeach;
                                    endif;
                                    ?>
                                </tbody>
                            </table>

                        </div>
                    </div>


                    <nav aria-label="Page navigation">
                        <?php
                        $totalRegistros = $postController->RetornaQtdPost();
                        $totalRegistros;
                        if ($totalRegistros <= $quantidade):

                        else:
                            $paginas = ceil($totalRegistros / $quantidade);
                            $links = 5;

                            if (isset($i)):
                            else:
                                $i = '1';
                            endif;
                            ?>

                            <style>
    <?php
    if (isset($_GET['pg'])):
        $num_pg = $_GET['pg'];
    endif;
    ?>
                                .pagination a.active<?php echo $num_pg; ?>{background-color: #68b3c8; color: #fff; }
                            </style>
                            <ul class="pagination">
                                <li><a href="dashboard.php?pagina=listarPost&pg=1" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                <?php
                                if (isset($_GET['pg'])):
                                    $num_pg = $_GET['pg'];
                                endif;

                                for ($i = $pg - $links; $i <= $pg - 1; $i++):
                                    if ($i <= 0):
                                    else:
                                        ?>                            
                                        <li class="active<?= $i; ?>"><a href="dashboard.php?pagina=listarPost&pg=<?= $i; ?>"><?= $i; ?> <span class="sr-only">(current)</span></a></li>
                                    <?php
                                    endif;
                                endfor;
                                ?>       
                                <li><a class="active<?= $i; ?>" href="dashboard.php?pagina=listarPost&pg=<?= $i; ?>"><?= $pg; ?></a></li>
                                <?php
                                for ($i = $pg + 1; $i <= $pg = $links; $i++):
                                    if ($i > $paginas):
                                    else:
                                        ?>
                                        <li><a class="active//<?= $i; ?>" href="dashboard.php?pagina=listarPost&pg=<?= $i; ?>"><?= $i; ?></a></li>
                                        <?php
                                        endif;
                                    endfor;
                                    ?>                    
                                <li>
                                    <a href="dashboard.php?pagina=listarPost&pg=<?= $paginas; ?>" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            </ul>
                        <?php
                        endif;
                        ?>
                    </nav>
                </div>



            </div>
        </div>
    </div>

